version: '3'
services:
  dev:
    build: .
    volumes:
      - .:/app
      - go-cache:/root/go
    command: tail -f /dev/null  # Keeps container running for development

volumes:
  go-cache:  # Persistent volume for Go modules cache 