# Default values for hubble-mapper
image:
  registry: docker.io
  repository: your-registry
  tag: latest
  pullPolicy: Always

cni:
  subnet: "10.244.0.0/16"
  bridge: "hubble0"

grpcServer:
  port: 50051
  replicas: 1

agent:
  image:
    repository: ghcr.io/depmap/depmap-agent
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

server:
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

relay:
  image:
    repository: ghcr.io/depmap/depmap-relay
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 4245

depmap:
  bpf:
    mountPath: /sys/fs/bpf
    configMap:
      name: depmap-bpf-objects

serviceAccount:
  create: true
  name: depmap

rbac:
  create: true

tolerations: []
nodeSelector: {} 