# Default values for hubble-mapper
image:
  registry: docker.io
  repository: your-registry
  tag: latest
  pullPolicy: Always

cni:
  subnet: "10.244.0.0/16"
  bridge: "hubble0"

grpcServer:
  port: 50051
  replicas: 1

agent:
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

server:
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi" 