apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hubble-flow-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: hubble-flow-agent
    {{- include "hubble-mapper.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: hubble-flow-agent
  template:
    metadata:
      labels:
        app: hubble-flow-agent
    spec:
      hostNetwork: true
      containers:
      - name: agent
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/hubble-flow-agent:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
        resources:
          {{- toYaml .Values.agent.resources | nindent 12 }}
        volumeMounts:
        - name: bpf-fs
          mountPath: /sys/fs/bpf
        - name: cni-bin
          mountPath: /opt/cni/bin
        - name: cni-conf
          mountPath: /etc/cni/net.d
      volumes:
      - name: bpf-fs
        hostPath:
          path: /sys/fs/bpf
          type: DirectoryOrCreate
      - name: cni-bin
        hostPath:
          path: /opt/cni/bin
          type: DirectoryOrCreate
      - name: cni-conf
        hostPath:
          path: /etc/cni/net.d
          type: DirectoryOrCreate 