apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "depmap.fullname" . }}-agent
  labels:
    {{- include "depmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  selector:
    matchLabels:
      {{- include "depmap.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        {{- include "depmap.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: agent
    spec:
      serviceAccountName: {{ include "depmap.serviceAccountName" . }}
      hostNetwork: true
      hostPID: true
      containers:
        - name: agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          volumeMounts:
            - name: bpf-fs
              mountPath: {{ .Values.depmap.bpf.mountPath }}
            - name: bpf-programs
              mountPath: /opt/depmap/bpf
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
      volumes:
        - name: bpf-fs
          hostPath:
            path: {{ .Values.depmap.bpf.mountPath }}
            type: Directory
        - name: bpf-programs
          configMap:
            name: {{ .Values.depmap.bpf.configMap.name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 