apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubble-grpc-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: hubble-grpc-server
    {{- include "hubble-mapper.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.grpcServer.replicas }}
  selector:
    matchLabels:
      app: hubble-grpc-server
  template:
    metadata:
      labels:
        app: hubble-grpc-server
    spec:
      containers:
      - name: server
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/hubble-grpc-server:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.grpcServer.port }}
        resources:
          {{- toYaml .Values.server.resources | nindent 12 }} 