apiVersion: v1
kind: Service
metadata:
  name: {{ include "depmap.fullname" . }}-relay
  labels:
    {{- include "depmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: relay
spec:
  type: {{ .Values.relay.service.type }}
  ports:
    - port: {{ .Values.relay.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "depmap.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: relay 