apiVersion: v1
kind: Service
metadata:
  name: hubble-grpc-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: hubble-grpc-server
    {{- include "hubble-mapper.labels" . | nindent 4 }}
spec:
  selector:
    app: hubble-grpc-server
  ports:
  - port: {{ .Values.grpcServer.port }}
    targetPort: {{ .Values.grpcServer.port }}
    protocol: TCP
    name: grpc 